apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: manikanta44/api-gateway:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://monitor-service:8080
            # Expose all actuator endpoints
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"

            # Ensure health details are shown
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: ALWAYS

            # Management port (same as app port to serve /actuator from same port)
            - name: MANAGEMENT_SERVER_PORT
              value: "9090"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL
              value: http://api-gateway:9090
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka:8761/eureka

          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservices
spec:
  selector:
    app: gateway
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
