apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: manikanta44/eureka-service:1.0.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://monitor-service:8080
            # Expose all actuator endpoints
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"

            # Ensure health details are shown
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: ALWAYS

            # Management port (same as app port to serve /actuator from same port)
            - name: MANAGEMENT_SERVER_PORT
              value: "8761"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL
              value: http://eureka:8761
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: microservices
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer
