apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: manikanta44/monitor-service:1.0.0
          env:
            - name: SPRING_PROFILES_DEFAULT
              value: dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  namespace: microservices
spec:
  selector:
    app: monitor
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
