spring:
  datasource:
    url: jdbc:mysql://mysql-service/order-db
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  boot:
    admin:
      client:
        url: http://monitor-service/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service/eureka