spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:8080/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka