server:
  port: 9091

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate', 'update', 'create', or 'create-drop' based on your use case
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always